// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGybTH68WNgBU6kYCcx0QnvZnumr2y96I',
    appId: '1:762995342662:web:5f84f44ca677e4adceb947',
    messagingSenderId: '762995342662',
    projectId: 'jeclebase-8fe6f',
    authDomain: 'jeclebase-8fe6f.firebaseapp.com',
    storageBucket: 'jeclebase-8fe6f.appspot.com',
    measurementId: 'G-Y88Z4FCLT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAClyBvQBvmnoe7aWxBiVDUHLXe9VaS0KI',
    appId: '1:762995342662:android:769cb98116d7bcd4ceb947',
    messagingSenderId: '762995342662',
    projectId: 'jeclebase-8fe6f',
    storageBucket: 'jeclebase-8fe6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwi5vfhhQxGgakYqFcF3jFgMXb-S1wD-c',
    appId: '1:762995342662:ios:9458cf0c9d261549ceb947',
    messagingSenderId: '762995342662',
    projectId: 'jeclebase-8fe6f',
    storageBucket: 'jeclebase-8fe6f.appspot.com',
    iosBundleId: 'com.example.jecle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwi5vfhhQxGgakYqFcF3jFgMXb-S1wD-c',
    appId: '1:762995342662:ios:9458cf0c9d261549ceb947',
    messagingSenderId: '762995342662',
    projectId: 'jeclebase-8fe6f',
    storageBucket: 'jeclebase-8fe6f.appspot.com',
    iosBundleId: 'com.example.jecle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGybTH68WNgBU6kYCcx0QnvZnumr2y96I',
    appId: '1:762995342662:web:78a272a89931f2adceb947',
    messagingSenderId: '762995342662',
    projectId: 'jeclebase-8fe6f',
    authDomain: 'jeclebase-8fe6f.firebaseapp.com',
    storageBucket: 'jeclebase-8fe6f.appspot.com',
    measurementId: 'G-6R9RW57W18',
  );
}
